In [1]:
SPEED_OF_LIGHT = 2.99792458e8
import sys
sys.path.append('../')
# from laika.gps_time import GPSTime
import numpy as np
data = {'xyz': np.array([[-2.12076291e+07, -9.33335451e+06, -1.05950495e+07],
       [-1.29227003e+03, -6.96221360e+02,  3.20310954e+03],
       [ 1.48412922e-01,  1.81894435e-01,  1.27705866e-01],
       [ 1.29059048e-05, -5.02752334e-06, -1.28606187e-05],
       [-4.17123328e-10, -7.55894967e-10, -2.58892017e-10],
       [-3.43159884e-14,  1.67876905e-14,  1.56369929e-14],
       [ 6.73595570e-19,  1.31533281e-18,  2.19636061e-19],
       [ 4.34203069e-23, -2.13589735e-23, -9.41090611e-24],
       [-6.26091511e-28, -1.25008382e-27, -1.17180678e-28],
       [-3.33567213e-32,  1.45266321e-32,  4.08768116e-33],
       [ 6.56898962e-37,  7.38556230e-38, -2.47099723e-37],
       [ 1.51325616e-41,  1.95795196e-41, -9.61653778e-42],
       [-9.84137744e-45,  2.30451999e-44,  1.01651260e-44],
       [ 5.74960604e-50, -4.15601106e-49,  1.24553870e-49],
       [ 1.54858071e-52, -3.69852478e-52, -1.60892262e-52],
       [-4.06726780e-58,  2.58131663e-57, -7.50186137e-58],
       [-9.62336789e-61,  2.27855188e-60,  9.93007482e-61]]), 'clock': [1.6027777777731984e-12, 0.00020527189499999998], 'deg': 16, 'deg_t': 1}
# time = GPSTime(week=2012, tow=404100.0)
dt = 2
deg = data['deg']
deg_t = data['deg_t']
indices = np.arange(deg+1)[:,np.newaxis]
# print(np.arange(deg+1), np.newaxis)
# print(indices)
sat_pos = np.sum((dt**indices)*data['xyz'], axis=0)
# print(dt**indices)
print((dt**indices)*data['xyz'])
indices = indices[1:]
sat_vel = np.sum(indices*(dt**(indices-1)*data['xyz'][1:]), axis=0)
print(range(deg_t+1))
time_err = sum((dt**p)*data['clock'][deg_t-p] for p in range(deg_t+1))
print(range(1, deg_t+1))
time_err_rate = sum(p*(dt**(p-1))*data['clock'][deg_t-p] for p in range(1,deg_t+1))
time_err_with_rel = time_err - 2*np.inner(sat_pos, sat_vel)/SPEED_OF_LIGHT**2

[[-2.12076291e+07 -9.33335451e+06 -1.05950495e+07]
 [-2.58454006e+03 -1.39244272e+03  6.40621908e+03]
 [ 5.93651688e-01  7.27577740e-01  5.10823464e-01]
 [ 1.03247238e-04 -4.02201867e-05 -1.02884950e-04]
 [-6.67397325e-09 -1.20943195e-08 -4.14227227e-09]
 [-1.09811163e-12  5.37206096e-13  5.00383773e-13]
 [ 4.31101165e-17  8.41812998e-17  1.40567079e-17]
 [ 5.55779928e-21 -2.73394861e-21 -1.20459598e-21]
 [-1.60279427e-25 -3.20021458e-25 -2.99982536e-26]
 [-1.70786413e-29  7.43763564e-30  2.09289275e-30]
 [ 6.72664537e-34  7.56281580e-35 -2.53030116e-34]
 [ 3.09914862e-38  4.00988561e-38 -1.96946694e-38]
 [-4.03102820e-41  9.43931388e-41  4.16363561e-41]
 [ 4.71007727e-46 -3.40460426e-45  1.02034530e-45]
 [ 2.53719464e-48 -6.05966300e-48 -2.63605882e-48]
 [-1.33276231e-53  8.45845833e-53 -2.45820993e-53]
 [-6.30677038e-56  1.49327176e-55  6.50777383e-56]]
range(0, 2)
range(1, 2)
